[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
gov_encrypt = "A71T7Y4SavyuEHg4yMLWELceX68PTyhwjWbFWy74w1Ah"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
