[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
gov_encrypt = "8FbVRnSmv1FtZvgYA4HjN7HN9BCQVZYuR3jf2sFsscgV"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "./.wallets/deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
